apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus-app:9090
    basicAuth: false
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki-app:3100
    isDefault: false
    jsonData:
      maxLines: 1000
    version: 1
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      serviceMap:
        datasourceUid: 'prometheus'
    version: 1
    editable: true
